RealEstate.Web/Controllers/PropertyTypesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RealEstate.Web.Common;
using RealEstate.Web.Constants;
using RealEstate.Web.Models;
using RealEstate.Web.Services.IServices;

namespace RealEstate.Web.Controllers
{
    [Authorize(Roles = RoleConstants.Role_Admin)]
    public class PropertyTypesController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly ITokenProvider _tokenProvider;
        private readonly IUserService _userService;

        public PropertyTypesController(HttpClient httpClient, ITokenProvider tokenProvider, IUserService userService)
        {
            _httpClient = httpClient;
            _tokenProvider = tokenProvider;
            _userService = userService;
            ApiRequestHelper.SetBearerToken(_httpClient, _tokenProvider.GetToken());
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AddPropertyType(int? id)
        {
            if (id == null)
            {
                var model = new PropertyType();
                return View("AddUpdatePropertyType", model);
            }
            var propertyTypeResponse = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/propertyTypes/GetPropertyType/{id}");
            if (propertyTypeResponse.IsSuccessStatusCode)
            {
                var propertyType = await propertyTypeResponse.Content.ReadFromJsonAsync<PropertyType>();
                return View("AddUpdatePropertyType", propertyType);
            }
            TempData["error"] = "Something went wrong while reading property type! Try again";
            return View("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPropertyType(PropertyType propertyType)
        {
            if (!ModelState.IsValid)
            {
                TempData["error"] = "Please fill all fields";
                ModelState.AddModelError("", "Invalid property type");
                return View("AddUpdatePropertyType", propertyType);
            }
            var response = await _httpClient.PostAsJsonAsync($"{APIGatewayUrl.URL}api/propertyTypes/AddPropertyType", propertyType);
            if (response.IsSuccessStatusCode)
            {
                TempData["success"] = "Property Type added succesfully";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Something went wrong! Try again";
            ModelState.AddModelError("", "Something went wrong");
            return View("AddUpdatePropertyType", propertyType);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdatePropertyType(PropertyType propertyType)
        {
            if (!ModelState.IsValid)
            {
                TempData["error"] = "Please fill all the fields";
                ModelState.AddModelError("", "Invalid property type");
                return View("AddUpdatePropertyType", propertyType);
            }
            var response = await _httpClient.PutAsJsonAsync($"{APIGatewayUrl.URL}api/propertyTypes/UpdatePropertyType", propertyType);
            if (response.IsSuccessStatusCode)
            {
                TempData["success"] = "Property type updated succesfully";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Something went wrong! Try again";
            ModelState.AddModelError("", "Something went wrong");
            return View("AddUpdatePropertyType", propertyType);

        }


        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var response = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/propertyTypes/GetPropertyType/{id}");
            if (response.IsSuccessStatusCode)
            {
                var propertyType = await response.Content.ReadFromJsonAsync<PropertyType>();
                return View(propertyType);
            }
            TempData["error"] = "Something went wrong while reading property type data! Try again";
            return RedirectToAction("Index");
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var response = await _httpClient.DeleteAsync($"{APIGatewayUrl.URL}api/propertyTypes/DeletePropertyType/{id}");
            if (response.IsSuccessStatusCode)
            {
                TempData["success"] = "Property type deleted successfully";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Something went wrong! Try again";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> GetPropertyTypes()
        {
            var response = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/propertyTypes/GetPropertyTypes");
            if (response.IsSuccessStatusCode)
            {
                var propertyTypes = await response.Content.ReadFromJsonAsync<List<PropertyType>>();
                return new JsonResult(propertyTypes);
            }
            return Json(null);
        }
    }
}

RealEstate.Web/Views/PropertyTypes/AddUpdatePropertyType.cshtml
@model PropertyType

@{
    var action = " ";
    if (Model.Id == 0)
    {
        action = "AddPropertyType";
    }
    else
    {
        action = "UpdatePropertyType";
    }
}

<div class="content">
    <partial name="_Navbar" />
    <div class="row">
        <div>
            <span id="close" style="float:right" class="hidden-sm hidden-xs">
                <span id="expand">CloseHelp</span>
                <i class="fa fa-chevron-right" id="icon-expand" aria-hidden="true" onclick="OpenHelp()"></i>
            </span>
        </div>
        <div class="col-md-9" id="left-side-bar">
            <div class="container-fluid pt-4 px-4 col-12 justify-content-between">
                <div class="row mb-3">
                    <div class="col-10">
                        <ol class="breadcrumb float-sm-right col-10 text-start">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item"><a href="#">Property Types</a></li>
                            @if (Model.Id == 0)
                            {
                                <li class="breadcrumb-item active">Add</li>
                            }
                            else
                            {
                                <li class="breadcrumb-item">Edit</li>
                                <li class="breadcrumb-item active">@Model.Id</li>

                            }
                        </ol>
                    </div>
                    <div class="col-2 text-end">
                        <a  asp-controller="PropertyTypes" asp-action="Index" class="btn btn-primary ">Back to list</a>
                    </div>
                </div>
                <form asp-controller="PropertyTypes" asp-action="@action" method="post">
                    <input type="hidden" asp-for="Id" />

                    <div class="d-flex row">

                        <div class="form-floating mb-3  ">
                            <input type="text" asp-for="Name" class="form-control help-sidebar" data-title="Property Type Name" data-description="Enter the name of Property type" id="floatingText" placeholder="text">
                            <label for="floatingText">&nbsp; Name</label>
                            <span asp-validation-for="@Model.Name" class="text-danger"></span>
                        </div>
                    </div>

                    @if (Model.Id == 0)
                    {
                        <button type="submit" class="btn btn-primary py-3 w-100 mb-4 col-sm-6">Add Property</button>

                    }
                    else
                    {
                        <button type="submit" class="btn btn-secondary py-3 w-100 mb-4 col-sm-6">Update</button>

                    }
                </form>
            </div>
        </div>
        <div class="col-md-3 navbar-right hidden-sm hidden-xs help-bar remove-left-padding" id="right-sidebar">
            <div class=" card-primary">
                <div class="card-header">
                    <h3 class="card-title"><span id="title">QuickHelp</span></h3>
                </div>
                <div class="card-body">
                    <p id="description">
                        @(Model.Id == 0 ? "Property Type Add Form" : "Property Type Edit Form")
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    <script>
        $(document).ready(function () {

            //if (localStorage.isHelpVisible == 'true') {
            //    Close();
            //}
            //else {
            //    Open();
            //}
            $(window).scroll(function () {
                $("#right-sidebar").css("margin-top", Math.max(0, $(this).scrollTop() - 112));
            });

            $(".help-sidebar").click(function () {
                var event = $(this);
                var title = $(this).attr("data-title");
                var description = $(this).attr("data-description");
                HelpSideBar(title, description);
            });

            //Function that fill help right side bar
            function HelpSideBar(title, description) {
                //debugger;
                $("#title").text(title);
                $("#description").text(description);
            }

            $("#close").click(function () {
                if ($("#right-sidebar").is(':visible')) {
                    Open();
                }
                else {
                    Close();
                }
            });

            function Open() {

                var option = { direction: 'right' };
                $("#right-sidebar").hide();
                $("#left-side-bar").removeClass("col-md-9");
                $("#left-side-bar").addClass("col-md-12");

                $("#icon-expand").removeClass("fa-chevron-right");
                $("#icon-expand").addClass("fa-chevron-left");
                $("#expand").html("OpenHelp");

                localStorage.isHelpVisible = false;
            }
            function Close() {
                //debugger;
                $("#left-side-bar").removeClass("col-md-12");
                $("#left-side-bar").addClass("col-md-9");
                var option = { direction: 'right' };
                $("#right-sidebar").show();
                $("#icon-expand").removeClass("fa-chevron-left");
                $("#icon-expand").addClass("fa-chevron-right");
                $("#expand").html("CloseHelp");

                localStorage.isHelpVisible = true;
            }
        });
    </script>
}

RealEstate.Web/Views/PropertyTypes/Index.cshtml
@section Styles{
    <!-- DataTables -->
    <link rel="stylesheet" href="~/theme/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/theme/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/theme/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

    <link rel="stylesheet" href="//cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" />
    <!-- jQuery Confirm -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
}
<div class="content">
    <partial name="_Navbar" />
    <div class="container-fluid pt-4 px-4 col-12">
        <!-- Content Header (Page header) -->
        <div class="row">
            @* <div class="col-sm-6 col-xl-3 ">
            @*<h1>Users</h1>
            </div>*@
            <div class="col-6">
                <ol class="breadcrumb float-sm-right col-6 text-start ">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Property Types</li>
                </ol>
            </div>
            <div class="col-6 text-end">
                <a  asp-action="AddPropertyType" asp-controller="PropertyTypes" class="btn btn-primary"> <i class="bi bi-plus-circle"></i>&nbsp; Add Property Type</a>
            </div>
        </div>
    </div>

    <div class="container-fluid pt-4 px-4 col-12">
        <!-- Main content -->

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Property Types List</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="propertyTypes-list" class="table table-bordered table-striped table-hover">
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
        <!-- /.container-fluid -->
    </div>
</div>

<!-- /.content -->
@section Scripts{
    <script src="~/theme/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/theme/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/theme/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/theme/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/theme/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/theme/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/theme/plugins/jszip/jszip.min.js"></script>
    <script src="~/theme/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/theme/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/theme/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/theme/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/theme/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <script src="//cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://kit.fontawesome.com/a68cad6f07.js" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <!-- jQuery Confirm -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    <script src="~/js/propertyTypes.js"></script>
    }