RealEstate.Web/Controllers/PropertiesController.cs
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RealEstate.Web.Common;
using RealEstate.Web.Constants;
using RealEstate.Web.Models;
using RealEstate.Web.Models.Dtos;
using RealEstate.Web.Services.IServices;

namespace RealEstate.Web.Controllers
{
    [Authorize(Roles = RoleConstants.Role_User_Indi + "," + RoleConstants.Role_User_Comp)]
    public class PropertiesController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly IUserService _userService;
        private readonly ITokenProvider _tokenProvider;

        public PropertiesController(HttpClient httpClient, IUserService userService, ITokenProvider tokenProvider)
        {
            _httpClient = httpClient;
            _userService = userService;
            _tokenProvider = tokenProvider;
            ApiRequestHelper.SetBearerToken(_httpClient, _tokenProvider.GetToken());
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AddProperty(int? id)
        {
            string currentUserId = _userService.GetCurrentUser().Id;
            string currentUserRole = _userService.GetCurrentUserRole();
            var model = new AddPropertyViewModel();
            if (id == null)
            {
                model.Property = new PropertyViewModel();
                if (currentUserRole == RoleConstants.Role_User_Comp)
                {
                    var usersResponse = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/user/GetUsers/{currentUserId}");
                    if (usersResponse.IsSuccessStatusCode)
                    {
                        var users = await usersResponse.Content.ReadFromJsonAsync<List<UserDto>>();
                        model.UsersList = users!.Select(x => new SelectListItem { Text = x.Name, Value = x.Id });
                    }
                }
                var propertyTypesResponse = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/propertyTypes/GetPropertyTypes");
                if (propertyTypesResponse.IsSuccessStatusCode)
                {
                    var propertyTypes = await propertyTypesResponse.Content.ReadFromJsonAsync<List<PropertyType>>();
                    model.PropertyTypeList = propertyTypes!.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });
                }
                model.Cities = CityConstants._cities.Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Name
                });
                return View("AddUpdateProperty", model);
            }
            var response = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/property/GetProperty/{id}");
            if (response.IsSuccessStatusCode)
            {
                var property = await response.Content.ReadFromJsonAsync<PropertyViewModel>();
                model.Property = property!;
                if (currentUserRole == RoleConstants.Role_User_Comp)
                {
                    var usersResponse = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/user/GetUsers/{currentUserId}");
                    if (usersResponse.IsSuccessStatusCode)
                    {
                        var users = await usersResponse.Content.ReadFromJsonAsync<List<UserDto>>();
                        model.UsersList = users!.Select(x => new SelectListItem { Text = x.Name, Value = x.Id });
                    }
                }
                var propertyTypesResponse = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/propertyTypes/GetPropertyTypes");
                if (propertyTypesResponse.IsSuccessStatusCode)
                {
                    var propertyTypes = await propertyTypesResponse.Content.ReadFromJsonAsync<List<PropertyType>>();
                    model.PropertyTypeList = propertyTypes!.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });
                }
                model.Cities = CityConstants._cities.Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Name
                });
                return View("AddUpdateProperty", model);
            }
            return View("AddUpdateProperty");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddProperty(AddPropertyViewModel model)
        {
            if (!ModelState.IsValid)
            {
                TempData["error"] = "Invalid input. Please try again.";
                ModelState.AddModelError("Errors", "Invalid attempt");
                return RedirectToAction("AddProperty", model);
            }

            var currentUser = _userService.GetCurrentUser();
            var propertyDto = MapToPropertyDto(model, currentUser);

            var propertyCreationResponse = await CreateProperty(propertyDto, model.CoverImage, model.PropertyImages);

            if (propertyCreationResponse.IsSuccessStatusCode)
            {
                TempData["success"] = "Property added successfully";
                return RedirectToAction("Index");
            }

            TempData["error"] = "Failed to add property. Please try again.";
            return RedirectToAction("AddProperty", model);
        }

        private async Task<HttpResponseMessage> CreateProperty(PropertyDto propertyDto, IFormFile coverImage, IFormFileCollection propertyImages)
        {
            var propertyCreationResponse = await _httpClient.PostAsJsonAsync($"{APIGatewayUrl.URL}api/property/AddProperty", propertyDto);
            if (propertyCreationResponse.IsSuccessStatusCode)
            {
                var property = await propertyCreationResponse.Content.ReadFromJsonAsync<PropertyDto>();
                var imageUploadResponse = await UploadImages(property!.Id, coverImage, propertyImages);
                if (imageUploadResponse.IsSuccessStatusCode)
                {
                    return propertyCreationResponse;
                }
                await DeleteProperty(property.Id);
            }
            return propertyCreationResponse;
        }

        private PropertyDto MapToPropertyDto(AddPropertyViewModel model, UserDto currentUser)
        {
            return new PropertyDto
            {
                Id = model.Property.Id,
                Name = model.Property.Name,
                Description = model.Property.Description,
                BathRooms = model.Property.BathRooms,
                BedRooms = model.Property.BedRooms,
                Area = model.Property.Area,
                Price = model.Property.Price,
                Status = model.Property.Status,
                State = model.Property.State,
                City = model.Property.City,
                StreetAddress = model.Property.StreetAddress,
                CoverImageUrl = model.CoverImage.FileName,
                TransactionType = model.Property.TransactionType,
                UserId = model.Property.UserId,
                PropertyTypeId = model.Property.PropertyTypeId,
                CurrentUserId = currentUser.Id,
                CurrentUserRole = currentUser.Role!,
            };
        }

        private async Task<HttpResponseMessage> UploadImages(int propertyId, IFormFile coverImage, IFormFileCollection
         propertyImages)
        {
            var content = new MultipartFormDataContent { { new StreamContent(coverImage.OpenReadStream()), "CoverImage", coverImage.FileName } };
            foreach (var image in propertyImages)
            {
                content.Add(new StreamContent(image.OpenReadStream()), "PropertyImages", image.FileName);
            }
            return await _httpClient.PostAsync($"{APIGatewayUrl.URL}api/property/UploadImages/{propertyId}", content);
        }

        [HttpGet]
        public async Task<IActionResult> GetProperties()
        {
            var currentUserId = _userService.GetCurrentUser().Id;
            var currentUserRole = _userService.GetCurrentUser().Role;
            var properties = new List<PropertyViewModel>();
            var response = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/property/GetProperties/{currentUserId}/{currentUserRole}");
            if (response.IsSuccessStatusCode && response.StatusCode != System.Net.HttpStatusCode.NoContent)
            {
                properties = await response.Content.ReadFromJsonAsync<List<PropertyViewModel>>();

                foreach (var property in properties!)
                {
                    if (property.Status != PropertyStatus.Rented)
                    {
                        property.ShowButtons = true;
                    }
                    var userResponse = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/user/GetUser/{property.UserId}");
                    if (userResponse.IsSuccessStatusCode)
                    {
                        var user = await userResponse.Content.ReadFromJsonAsync<UserDto>();
                        property.User = new UserDto()
                        {
                            Name = user!.Name
                        };
                    }
                }
                return new JsonResult(properties);
            }
            return new JsonResult(properties);
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteProperty(int id)
        {
            var response = await _httpClient.DeleteAsync($"{APIGatewayUrl.URL}api/property/DeleteProperty/{id}");
            if (response.IsSuccessStatusCode)
            {
                return Json(new { success = true, message = "Delete Successful" });
            }
            return Json(new { success = false, message = "Delete Not Successful" });
        }

        [HttpGet]
        [AllowAnonymous]

RealEstate.Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RealEstate.Web.Common;
using RealEstate.Web.Constants;
using RealEstate.Web.Models;
using RealEstate.Web.Models.Dtos;
using RealEstate.Web.Services.IServices;

namespace RealEstate.Web.Controllers
{
    [Authorize(Roles = RoleConstants.Role_User_Comp + "," + RoleConstants.Role_Admin)]
    public class UserController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly IUserService _userService;
        private readonly ITokenProvider _tokenProvider;

        public UserController(HttpClient httpClient, IUserService userService, ITokenProvider tokenProvider)
        {
            _httpClient = httpClient;
            _userService = userService;
            _tokenProvider = tokenProvider;
            ApiRequestHelper.SetBearerToken(_httpClient, _tokenProvider.GetToken());
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> CreateUser(string? id)
        {
            if (id == null)
            {
                RegisterViewModel model = new RegisterViewModel();
                return View("CreateUpdateUser", model);
            }
            var response = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/user/GetUser/{id}");
            if (response.IsSuccessStatusCode)
            {
                var user = await response.Content.ReadFromJsonAsync<RegisterViewModel>();

                return View("CreateUpdateUser", user);
            }
            TempData["error"] = "Something went wrong when reading user! Try again";
            return View("CreateUpdateUser");
        }

        [HttpPost]
        public async Task<IActionResult> CreateUser(RegisterViewModel model)
        {
            ModelState.Remove("OldPassword");
            if (!ModelState.IsValid)
            {
                TempData["error"] = "Please fill all the fields";
                return View("CreateUpdateUser", model);
            }
            var currentUserRole = _userService.GetCurrentUser().Role;
            var currentUserId = _userService.GetCurrentUser().Id;

            CreateUserDto user = new CreateUserDto()
            {
                User = model,
                CurrentUserId = currentUserId,
                CurrentUserRole = currentUserRole!
            };


            var response = await _httpClient.PostAsJsonAsync($"{APIGatewayUrl.URL}api/user/CreateUser", user);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction(nameof(Index));
            }
            return View("CreateUpdateUser", model);
        }


        [HttpPost]
        public async Task<IActionResult> UpdateUser(RegisterViewModel model)
        {
            ModelState.Remove("Password");
            ModelState.Remove("ConfirmPassword");
            ModelState.Remove("OldPassword");
            if (!ModelState.IsValid)
            {
                TempData["error"] = "Please fill all the fields";
                return View("CreateUpdateUser", model);
            }
            var response = await _httpClient.PutAsJsonAsync($"{APIGatewayUrl.URL}api/user/UpdateUser", model);
            if (response.IsSuccessStatusCode)
            {
                TempData["success"] = "User updated succesfully";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "Something went wrong! Try again";
            return View("CreateUpdateUser", model);
        }




        [HttpGet]
        public async Task<IActionResult> GetUsersJson()
        {

            var currentUserRole = _userService.GetCurrentUser().Role;
            var currentUserId = _userService.GetCurrentUser().Id;
            var users = new List<UserDto>();

            if (currentUserRole == RoleConstants.Role_Admin)
            {
                var usersResponse = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/user/GetUsers/{currentUserId}/{currentUserRole}");
                if (usersResponse.IsSuccessStatusCode)
                {
                    users = await usersResponse.Content.ReadFromJsonAsync<List<UserDto>>();
                    return new JsonResult(users);
                }
            }
            var companyUsersResponse = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/user/GetUsersByCompanyId/{currentUserId}");
            if (companyUsersResponse.IsSuccessStatusCode)
            {
                users = await companyUsersResponse.Content.ReadFromJsonAsync<List<UserDto>>();
                return new JsonResult(users);
            }
            return new JsonResult(users);
        }

        public async Task<IActionResult> DeleteUser(string id)
        {
            var response = await _httpClient.DeleteAsync($"{APIGatewayUrl.URL}api/user/DeleteUser/{id}");
            if (response.IsSuccessStatusCode)
            {
                return new JsonResult(new { message = "Delete Successful", success = true });
            }
            return new JsonResult(new { message = "Delete Not Successful", success = false });
        }


    }
}

RealEstate.Web/Views/Shared/_Layout.cshtml
@using RealEstate.Web.Services.IServices;
@inject IUserService userService

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>PropManagePro</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/theme/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/theme/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/theme/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/theme/css/style.css" rel="stylesheet">
    <link href="~/css/site.css" />
    @*flag icon*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/css/flag-icon.min.css">


    <!-- Template Stylesheet -->
    <link href="~/theme/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    @RenderSection("Styles",false)
</head>

<body>
    @* qetu zevendesohet me current user *@
    @* !(userService.GetCurrentUser()!=null) *@
    @if (!User.Identity.IsAuthenticated)
    {
        <partial name="_Navbar" />

    }

    <div class="mx-3 px-3">
        <partial name="_Notification" />
       @* qetu zevendesohet me current user *@
        @* userService.GetCurrentUser() !=null *@
        @if (User.Identity.IsAuthenticated)
        {
            <partial name="_Sidebar" />

        }
        @RenderBody()


    </div>
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/theme/lib/chart/chart.min.js"></script>
    <script src="~/theme/lib/easing/easing.min.js"></script>
    <script src="~/theme/lib/waypoints/waypoints.min.js"></script>
    <script src="~/theme/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/theme/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/theme/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/theme/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://kit.fontawesome.com/a68cad6f07.js" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>



    <!-- Template Javascript -->
    <script src="~/theme/js/main.js"></script>
    @RenderSection("Scripts",false)
</body>

</html>

RealEstate.Web/Views/Shared/_Navbar.cshtml
@using Microsoft.AspNetCore.Identity
@using RealEstate.Web.Services.IServices;
@inject IUserService userService


@if (User.Identity.IsAuthenticated)
{
    <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-2">
        <a href="#" class="sidebar-toggler flex-shrink-0">
            <i class="fa fa-bars"></i>
        </a>
        <div class="navbar-nav align-items-center ms-auto">
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                    <img class="rounded-circle me-lg-2" src="~/theme/img/default-profile-picture.jpg" alt="" style="width: 40px; height: 40px;">
                    <span class="d-none d-lg-inline-flex">@User.Identity.Name</span>
                </a>
                <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                    <form asp-area="Individual" asp-action="Logout" asp-controller="Account" method="post">
                        <button type="submit" class="dropdown-item">Logout</button>
                    </form>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Register" asp-route-userId="@userService.GetCurrentUser().Id">Profile</a>
                    <a class="dropdown-item" asp-controller="Account" asp-action="ChangePassword" asp-route-userId="@userService.GetCurrentUser().Id">Change Password</a>
                </div>
            </div>
        </div>
    </nav>
}
else
{
    <nav class="navbar navbar-expand navbar-light sticky-top px-4 py-2" style="background-color:#25ABFF;">

        <a class="nav-link" style="color:white;" asp-controller="Home" asp-action="Index" asp-route-loggedIn="false">Properties</a>

        <ul class="navbar-nav align-items-center ms-auto">
            <li class="nav-item">
                <a class="nav-link" style="color:white;"  asp-controller="Account" asp-action="Register">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color:white;" asp-controller="Account" asp-action="Login">Login</a>
            </li>

        </ul>
    </nav>

}

RealEstate.Web/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>

}
@if (TempData["error"] != null)
{
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}

RealEstate.Web/Views/Shared/_Sidebar.cshtml
@using RealEstate.Web.Constants;
@using RealEstate.Web.Services.IServices;
@inject IUserService userService

@if (User.Identity.IsAuthenticated)
{

    <div class="sidebar pe-4 pb-3">
        <nav class="navbar bg-light navbar-light">
            <div class="navbar-brand mx-4 mb-3">
                <h3 class="text-primary">EstateVille</h3>
            </div>
            <div class="d-flex align-items-center ms-4 mb-4">
                <div class="position-relative">
                    <img class="rounded-circle" src="~/theme/img/default-profile-picture.jpg" alt="" style="width: 40px; height: 40px;">
                    <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                </div>
                <div class="ms-3">
                    <h6 class="mb-0">@User.Identity.Name</h6>
                    <span class="mt-2">@userService.GetCurrentUser().Role</span>
                </div>
            </div>
            <div class="navbar-nav w-100">
                @if (userService.GetCurrentUser().Role == RoleConstants.Role_Admin)
                {
                    <a asp-controller="User" asp-action="Index" class="nav-item nav-link"><i class="nav-icon fas fa-user me-2"></i>Users</a>
                    <a asp-controller="PropertyTypes" asp-action="Index" class="nav-item nav-link"><i class="fa fa-layer-group me-2"></i>PropertyTypes</a>
                }

                @if (userService.GetCurrentUser().Role == RoleConstants.Role_User_Indi || userService.GetCurrentUser().Role == RoleConstants.Role_User_Comp)
                {
                    <a asp-controller="Home" asp-action="Dashboard" class="nav-item nav-link"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <a asp-controller="Properties" asp-action="Index" class="nav-item nav-link"><i class="bi bi-house me-2"></i>My Properties</a>
                    <a asp-controller="Home" asp-action="Index" asp-route-loggedIn="true" class="nav-item nav-link"><i class="bi bi-house me-2"></i>Properties</a>
                    <a asp-controller="Transaction" asp-action="Index" class="nav-item nav-link"><i class="fa-sharp fa-solid fa-euro-sign"></i>Transactions</a>

                }
                @if (userService.GetCurrentUser().Role == RoleConstants.Role_User_Comp)
                {
                    <a asp-controller="User" asp-action="Index" class="nav-item nav-link"><i class="nav-icon fas fa-user me-2"></i>Agents</a>
                }
            </div>
        </nav>
    </div>
}