RealEstate.Web/Models/TransactionViewModel.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace RealEstate.Web.Models
{
    public class TransactionViewModel
    {
        public int Id { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }

        [StringLength(450)]
        public string? OwnerId { get; set; }

        [StringLength(450)]
        public string? BuyerId { get; set; }

        public int? PropertyId { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime RentStartDate { get; set; } = DateTime.Now;

        [Column(TypeName = "datetime")]
        [Required]
        public DateTime RentEndDate { get; set; } = DateTime.Now;

        [Column(TypeName = "decimal(18, 2)")]
        public decimal? RentPrice { get; set; }

        [Column(TypeName = "decimal(18, 2)")]
        public decimal TotalPrice { get; set; }

        [StringLength(50)]
        public string? Status { get; set; }

        public string TransactionType { get; set; } = null!;

        [NotMapped]
        public bool ShowButtons { get; set; }
    }
}

RealEstate.Web/Controllers/TransactionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RealEstate.Web.Common;
using RealEstate.Web.Constants;
using RealEstate.Web.Models;
using RealEstate.Web.Models.Dtos;
using RealEstate.Web.Services.IServices;

namespace RealEstate.Web.Controllers
{
    [Authorize(Roles = RoleConstants.Role_User_Indi + "," + RoleConstants.Role_User_Comp)]
    public class TransactionController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly IUserService _userService;
        private readonly ITokenProvider _tokenProvider;
        public TransactionController(HttpClient httpClient, IUserService userService, ITokenProvider tokenProvider)
        {
            _httpClient = httpClient;
            _userService = userService;
            _tokenProvider = tokenProvider;
            ApiRequestHelper.SetBearerToken(_httpClient, _tokenProvider.GetToken());
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AddTransaction(int propertyId)
        {
            var response = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/property/GetProperty/{propertyId}");
            if (response.IsSuccessStatusCode)
            {
                var property = await response.Content.ReadFromJsonAsync<PropertyViewModel>();
                AddTransactionViewModel transaction = new()
                {
                    Property = property!,
                    Transaction = new()
                };
                return View(transaction);
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddTransaction(AddTransactionViewModel model)
        {
            var errorMessage = string.Empty;
            if (ModelState.IsValid)
            {
                var transactionDto = new AddTransactionDto()
                {
                    PropertyId = model.Property.Id,
                    BuyerId = _userService.GetCurrentUser().Id,
                    OwnerId = model.Property.UserId!,
                    RentStartDate = model.Transaction.RentStartDate,
                    RentEndDate = model.Transaction.RentEndDate,
                    TransactionType = model.Transaction.TransactionType,
                    PropertyPrice = model.Property.Price,
                };

                var response = await _httpClient.PostAsJsonAsync($"{APIGatewayUrl.URL}api/transaction/AddTransaction", transactionDto);
                if (response.IsSuccessStatusCode)
                {
                    TempData["success"] = "Requeist is made successfully";
                    return RedirectToAction("Index");
                }
                var errorContent = await response.Content.ReadFromJsonAsync<Dictionary<string, string>>();

                // Assuming the error content has a "Message" property
                errorMessage = errorContent["message"];
            }
            TempData["error"] = errorMessage;
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> GetTransactions()
        {
            var currentUserId = _userService.GetCurrentUser().Id;
            var currentUserRole = _userService.GetCurrentUser().Role;
            var transactionList = new List<TransactionListViewModel>();

            var response = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/transaction/GetTransactions/{currentUserId}/{currentUserRole}");
            if (response.IsSuccessStatusCode)
            {
                var transactions = await response.Content.ReadFromJsonAsync<List<TransactionViewModel>>();
                foreach (var transaction in transactions!)
                {
                    var transactionToAdd = new TransactionListViewModel()
                    {
                        Id = transaction.Id,
                        TransactionType = transaction.TransactionType,
                        Status = transaction.Status!,
                        TotalPrice = transaction.TotalPrice,
                        RentPrice = transaction.RentPrice,
                    };

                    var buyer = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/user/GetUser/{transaction.BuyerId}");
                    if (buyer.IsSuccessStatusCode)
                    {
                        var buyerUser = await buyer.Content.ReadFromJsonAsync<UserDto>();
                        transactionToAdd.BuyerName = buyerUser!.Name;
                    }
                    var owner = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/user/GetUser/{transaction.OwnerId}");
                    if (owner.IsSuccessStatusCode)
                    {
                        var ownerUser = await owner.Content.ReadFromJsonAsync<UserDto>();
                        transactionToAdd.OwnerName = ownerUser!.Name;
                    }
                    var property = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/property/GetProperty/{transaction.PropertyId}");
                    if (property.IsSuccessStatusCode)
                    {
                        var propertyDetails = await property.Content.ReadFromJsonAsync<PropertyViewModel>();
                        transactionToAdd.PropertyName = propertyDetails!.Name;
                    }
                    if (transaction.OwnerId == currentUserId && transaction.Status != TransactionStatus.Sold && transaction.Status != TransactionStatus.Rented && transaction.Status != TransactionStatus.Denied && transaction.Status != TransactionStatus.Expired)
                    {
                        transactionToAdd.ShowButtons = true;
                    }

                    transactionList.Add(transactionToAdd);
                }
                return new JsonResult(transactionList);
            }
            return new JsonResult(transactionList);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            TransactionDetailsViewModel transactionDetails = new();
            var response = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/transaction/GetTransaction/{id}");
            if (response.IsSuccessStatusCode)
            {
                var transaction = await response.Content.ReadFromJsonAsync<TransactionViewModel>();
                transactionDetails.Transaction = transaction!;
                var property = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/property/GetProperty/{transaction!.PropertyId}");
                if (property.IsSuccessStatusCode)
                {
                    var propertyDetails = await property.Content.ReadFromJsonAsync<PropertyViewModel>();
                    transactionDetails.Property = propertyDetails!;
                }
                var buyer = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/user/GetUser/{transaction.BuyerId}");
                if (buyer.IsSuccessStatusCode)
                {
                    var buyerDetails = await buyer.Content.ReadFromJsonAsync<UserDto>();
                    transactionDetails.Buyer = buyerDetails!;
                }
                var owner = await _httpClient.GetAsync($"{APIGatewayUrl.URL}api/user/GetUser/{transaction.OwnerId}");
                if (owner.IsSuccessStatusCode)
                {
                    var ownerDetails = await owner.Content.ReadFromJsonAsync<UserDto>();
                    transactionDetails.Owner = ownerDetails!;
                }

                return View(transactionDetails);
            }
            else
            {
                return View();
            }
        }

        public async Task<IActionResult> ApproveRequest(int id)
        {
            var response = await _httpClient.PostAsync($"{APIGatewayUrl.URL}api/transaction/ApproveRequest/{id}", null);
            if (response.IsSuccessStatusCode)
            {
                TempData["success"] = "Request is approved successfully";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Something went wrong!";
            return View(nameof(Index));
        }

        public async Task<IActionResult> RejectRequest(int id)
        {
            var response = await _httpClient.PostAsync($"{APIGatewayUrl.URL}api/transaction/DenyRequest/{id}", null);
            if (response.IsSuccessStatusCode)
            {
                TempData["success"] = "Request is denied successfully";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Something went wrong!";
            return View(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var response = await _httpClient.DeleteAsync($"{APIGatewayUrl.URL}api/transaction/DeleteTransaction/{id}");
            if (response.IsSuccessStatusCode)
            {
                TempData["success"] = "Transaction is Deleted successfully";
                return RedirectToAction("Index");

            }
            TempData["error"] = "Something went wrong!";
            return View(nameof(Index));
        }
    }
}

RealEstate.Web/Views/Transaction/AddTransaction.cshtml
@using RealEstate.Web.Constants;
@model AddTransactionViewModel

@{
    var buttonName = "";
    if (Model.Property.TransactionType == TransactionTypes.Rent)
    {
        buttonName = "Request to Rent Property";
    }
    else
    {
        buttonName = "Request to buy Property";
    }
}
<div class="content">
    <partial name="_Navbar" />
    <div class="container-fluid pt-4 px-4 col-12 justify-content-between">
        <div class="row mb-3">
            @* <div class="col-10">
            <ol class="breadcrumb float-sm-right col-10 text-start">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Users</a></li>
            @if (string.IsNullOrEmpty(Model.Id))
            {
            <li class="breadcrumb-item active">Add</li>
            }
            else
            {
            <li class="breadcrumb-item">Edit</li>
            <li class="breadcrumb-item active">Id</li>

            }
            </ol>
            </div>*@
            <div class="col-2 text-end">
                <a a asp-controller="Properties" asp-action="Details" asp-route-propertyId="@Model.Property.Id"
                    class="btn btn-primary ">Back to Property</a>
            </div>
        </div>
        <form asp-controller="Transaction" asp-action="AddTransaction" method="post">
            <input type="hidden" asp-for="Transaction.Id" />
            <input type="hidden" asp-for="Property.Id" />
            <input type="hidden" asp-for="Property.UserId" />
            <input type="hidden" asp-for="Property.TransactionType" />
            <input type="hidden" asp-for="Property.PropertyType" />
            <input type="hidden" asp-for="Property.Price" />
            <input type="hidden" asp-for="Property.State" />
            <input type="hidden" asp-for="Property.PropertyTypeId" />
            <input type="hidden" asp-for="Transaction.TransactionType" value="@Model.Property.TransactionType" />
            <div class="row">
                <div class="form-floating mb-3 col-sm-6 ">
                    <input readonly asp-for="Property.Name" class="form-control" id="floatingInput">
                    <label for="floatingInput">Property Name</label>
                </div>
                <div class="form-floating mb-3 col-sm-6 ">
                    <input readonly asp-for="Property.Price" class="form-control" id="floatingInput">
                    <label for="floatingInput">Price</label>
                </div>
            </div>


            <div class="col-lg-12 col-12">
                <div class="form-floating mb-3">
                    <textarea readonly rows="3" asp-for="Property.Description" class="form-control"></textarea>
                    <label>Description</label>
                </div>
            </div>

            <div class="d-flex row">
                <div class="form-floating mb-3  col-sm-6 ">
                    <input readonly asp-for="Property.BedRooms" class="form-control" id="floatingText"
                        placeholder="text">
                    <label for="floatingText">&nbsp; BedRooms</label>
                </div>
                <div class="form-floating mb-3 col-sm-6">
                    <input readonly asp-for="Property.BathRooms" class="form-control" id="floatingText"
                        placeholder="Password">
                    <label for="floatingText">&nbsp; BathRooms</label>
                </div>
            </div>
            <div class="row justify-content-between">
                <div class="form-floating mb-3 col-sm-6">
                    <input readonly asp-for="Property.Area" class="form-control" id="floatingText"
                        placeholder="Password">
                    <label for="floatingText">&nbsp; Area(in m&sup2;)</label>
                </div>

                <div class="form-floating mb-3 col-sm-6">
                    <input readonly asp-for="Property.Status" class="form-control" id="floatingText"
                        placeholder="Password">
                    <label for="floatingText">&nbsp; Status</label>
                </div>
            </div>
            <div class="row">
                <div class="form-floating mb-3 col-sm-6">
                    <input readonly asp-for="Property.City" class="form-control" id="floatingText"
                        placeholder="Password">
                    <label for="floatingText">&nbsp; City</label>
                </div>
                <div class="form-floating mb-3 col-sm-6">
                    <input readonly asp-for="Property.StreetAddress" class="form-control" id="floatingText"
                        placeholder="Password">
                    <label for="floatingText">&nbsp; Street Address</label>
                </div>
            </div>
            <div class="row">
                <div class="form-floating mb-3 col-sm-6">
                    <input readonly asp-for="Property.PropertyType!.Name" class="form-control" id="floatingText"
                        placeholder="Password">
                    <label for="floatingText">&nbsp; Property Type</label>
                </div>
                <div class="form-floating mb-3 col-sm-6">
                    <input readonly asp-for="Property.TransactionType" class="form-control" id="floatingText"
                        placeholder="Password">
                    <label for="floatingText">&nbsp;Transaction Type</label>
                </div>
            </div>
            @if (Model.Property.TransactionType == TransactionTypes.Rent)
            {
                <div class="row">
                    <div class="form-floating mb-3 col-sm-6">
                        <input type="date" asp-for="Transaction.RentStartDate" class="form-control" id="floatingText"
                            placeholder="Password">
                        <label for="floatingText">&nbsp; Rent Start Date</label>
                        <span asp-validation-for="Transaction.RentStartDate" class="text-danger"></span>
                    </div>
                    <div class="form-floating mb-3 col-sm-6">
                        <input type="date" asp-for="Transaction.RentEndDate" class="form-control" id="floatingText"
                            placeholder="Password">
                        <label for="floatingText">&nbsp; Rent End Date </label>
                        <span asp-validation-for="Transaction.RentEndDate" class="text-danger"></span>

                    </div>
                </div>
            }
            <button type="submit" class="btn btn-primary py-3 w-100 mb-4 col-sm-6">@buttonName</button>
        </form>
    </div>
</div>

@*@section Scripts{
<partial name="_ValidationScriptsPartial" />
}*@

RealEstate.Web/Views/Transaction/Details.cshtml
@using RealEstate.Web.Constants;
@model TransactionDetailsViewModel

@{
    var owner = "";
    var buyer = "";
    if (Model.Transaction.TransactionType == TransactionTypes.Rent)
    {
        owner = "Lessee";
        buyer = "Lessor";
    }
    else
    {
        owner = "Seller";
        buyer = "Buyer";
    }
}
<div class="content">
    <partial name="_Navbar" />
    <div class="container-fluid pt-4 px-4 col-12 justify-content-between">
        <div class="row mb-3">
            <div class="text-start">
                <a asp-area="Company" asp-controller="Transaction" asp-action="Index" class="btn btn-primary ">Back to
                    List</a>
            </div>
        </div>
        <form>
            <input disabled type="hidden" asp-for="Transaction.Id" />
            <input disabled type="hidden" asp-for="Property.Id" />
            <input disabled type="hidden" asp-for="Property.UserId" />
            <input disabled type="hidden" asp-for="Property.TransactionType" />
            <div class="row">
                <div class="form-floating mb-3 col-sm-6 ">
                    <input disabled asp-for="Buyer.Name" class="form-control" id="floatingInput">
                    <label for="floatingInput">&nbsp; @buyer</label>
                </div>
                <div class="form-floating mb-3 col-sm-6 ">
                    <input disabled asp-for="Owner.Name" class="form-control" id="floatingInput">
                    <label for="floatingInput">&nbsp;@owner</label>
                </div>
            </div>
            <div class="row">
                <div class="form-floating mb-3 col-sm-6 ">
                    <input disabled asp-for="Property.Name" class="form-control" id="floatingInput">
                    <label for="floatingInput">&nbsp;Property Name</label>
                </div>
                <div class="form-floating mb-3 col-sm-6 ">
                    <input disabled asp-for="Property.Price" class="form-control" id="floatingInput">
                    <label for="floatingInput">&nbsp;Price</label>
                </div>
            </div>


            <div class="col-lg-12 col-12">
                <div class="form-floating mb-3">
                    <textarea disabled rows="3" asp-for="Property.Description" class="form-control"></textarea>
                    <label>Description</label>
                </div>
            </div>

            <div class="d-flex row">
                <div class="form-floating mb-3  col-sm-6 ">
                    <input disabled asp-for="Property.BedRooms" class="form-control" id="floatingText"
                        placeholder="text">
                    <label for="floatingText">&nbsp; BedRooms</label>
                </div>
                <div class="form-floating mb-3 col-sm-6">
                    <input disabled asp-for="Property.BathRooms" class="form-control" id="floatingText"
                        placeholder="Password">
                    <label for="floatingText">&nbsp; BathRooms</label>
                </div>
            </div>
            <div class="row justify-content-between">
                <div class="form-floating mb-3 col-sm-6">
                    <input disabled asp-for="Property.Area" class="form-control" id="floatingText"
                        placeholder="Password">
                    <label for="floatingText">&nbsp; Area(in m&sup2;)</label>
                </div>

                <div class="form-floating mb-3 col-sm-6">
                    <input disabled asp-for="Property.Status" class="form-control" id="floatingText"
                        placeholder="Password">
                    <label for="floatingText">&nbsp; Status</label>
                </div>
            </div>
            <div class="row">
                <div class="form-floating mb-3 col-sm-6">
                    <input disabled asp-for="Property.City" class="form-control" id="floatingText"
                        placeholder="Password">
                    <label for="floatingText">&nbsp; City</label>
                </div>
                <div class="form-floating mb-3 col-sm-6">
                    <input disabled asp-for="Property.StreetAddress" class="form-control" id="floatingText"
                        placeholder="Password">
                    <label for="floatingText">&nbsp; Street Address</label>
                </div>
            </div>
            <div class="row">
                <div class="form-floating mb-3 col-sm-6">
                    <input disabled asp-for="Property.PropertyType!.Name" class="form-control" id="floatingText"
                        placeholder="Password">
                    <label for="floatingText">&nbsp; Property Type</label>
                </div>
                <div class="form-floating mb-3 col-sm-6">
                    <input disabled asp-for="Property.TransactionType" class="form-control" id="floatingText"
                        placeholder="Password">
                    <label for="floatingText">&nbsp;Transaction Type</label>
                </div>
            </div>
            @if (Model.Property.TransactionType == TransactionTypes.Rent)
            {
                <div class="row">
                    <div class="form-floating mb-3 col-sm-6">
                        <input disabled type="date" asp-for="Transaction.RentStartDate" class="form-control"
                            id="floatingText" placeholder="Password">
                        <label for="floatingText">&nbsp; Rent Start Date</label>
                    </div>
                    <div class="form-floating mb-3 col-sm-6">
                        <input disabled type="date" asp-for="Transaction.RentEndDate" class="form-control" id="floatingText"
                            placeholder="Password">
                        <label for="floatingText">&nbsp; Rent End Date </label>

                    </div>
                </div>
            }
        </form>
    </div>
</div>

RealEstate.Web/Views/Transaction/Index.cshtml
@section Styles{
    <!-- DataTables -->
    <link rel="stylesheet" href="~/theme/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/theme/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/theme/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

    <link rel="stylesheet" href="//cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" />
    <!-- jQuery Confirm -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
}
<div class="content">
    <partial name="_Navbar" />
    <div class="container-fluid pt-4 px-4 col-12">
        <!-- Content Header (Page header) -->
        <div class="row">
            @* <div class="col-sm-6 col-xl-3 ">
            @*<h1>Users</h1>
            </div>*@
            <div class="col-6">
                <ol class="breadcrumb float-sm-right col-6 text-start ">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Transactions</li>
                </ol>
            </div>
            @* <div class="col-6 text-end">
            <a asp-area="Transaction" asp-action="Upsert" asp-controller="Properties" class="btn btn-primary"><i class="bi bi-plus-circle"></i>&nbsp; Add Property</a>
            </div>*@
        </div>
    </div>

    <div class="container-fluid pt-4 px-4 col-12">
        <!-- Main content -->

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Transactions List</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="transactions-list" class="table table-bordered table-striped table-hover">
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
        <!-- /.container-fluid -->
    </div>
</div>

<!-- /.content -->
@section Scripts{
    <script src="~/theme/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/theme/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/theme/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/theme/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/theme/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/theme/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/theme/plugins/jszip/jszip.min.js"></script>
    <script src="~/theme/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/theme/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/theme/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/theme/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/theme/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <script src="//cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://kit.fontawesome.com/a68cad6f07.js" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <!-- jQuery Confirm -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    <script src="~/js/transactions.js"></script>
    }